import { Component, computed, inject, input, resource } from '@angular/core';
import { NgOptimizedImage } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { catchError, firstValueFrom, of } from 'rxjs';
import { MatListModule } from '@angular/material/list';
import { Cosplays } from '../cosplays';
import { stripAssetsPrefix } from '../legacy-image-path';
import { GalleryPhoto, PhotoGallery } from '../photo-gallery/photo-gallery';
import { LoadingSpinner } from '../loading-spinner/loading-spinner';

// Per-image pixel dimensions, generated by a one-off script that reads
// each JPEG's real width/height straight from its file header — see
// public/cosplay/{id}/dimensions.json. PhotoSwipe needs these up front
// for its zoom math, and there was no practical way to hand-annotate
// thousands of existing photos.
type DimensionsManifest = Record<string, { width: number; height: number }>;

const PLACEHOLDER_SRC = 'placeholder.gif';

@Component({
  selector: 'app-cosplay-details',
  imports: [MatListModule, NgOptimizedImage, PhotoGallery, LoadingSpinner],
  templateUrl: './cosplay-details.html',
  styleUrl: './cosplay-details.scss',
})
export class CosplayDetails {
  private readonly cosplaysService = inject(Cosplays);
  private readonly http = inject(HttpClient);

  protected readonly placeholderSrc = PLACEHOLDER_SRC;

  id = input<string>();

  // params() returning undefined (before the route has an id bound
  // yet) means the loader is skipped entirely rather than called with
  // an invalid id — Angular re-runs the loader whenever id() changes,
  // e.g. navigating from one cosplay's detail page to another's.
  protected readonly cosplayResource = resource({
    params: () => this.id(),
    loader: ({ params }) => this.cosplaysService.byId(params),
  });

  // dimensions.json lives alongside that cosplay's own images in the
  // public folder, so it's just a static file fetch — no Firestore or
  // Angular service involved. Uses HttpClient rather than a bare
  // fetch() because this app renders on the server too: fetch() can't
  // resolve a relative URL with no page to resolve it against and
  // throws "Failed to parse URL" during SSR, while HttpClient knows
  // how to resolve relative URLs correctly in both contexts.
  protected readonly dimensionsResource = resource({
    params: () => this.id(),
    loader: ({ params }) =>
      firstValueFrom(
        this.http
          .get<DimensionsManifest>(`cosplay/${params}/dimensions.json`)
          .pipe(catchError(() => of<DimensionsManifest>({}))),
      ),
  });

  // mainImgUrl is a leftover from the old app's Firestore data, e.g.
  // "assets/cosplay/{id}/1.jpg" — the new app serves images straight
  // from the public root (no "assets/" folder), so we strip that prefix
  // rather than migrating every document in Firestore.
  protected readonly mainImgSrc = computed(() =>
    stripAssetsPrefix(this.cosplayResource.value()?.mainImgUrl),
  );

  protected readonly galleryPhotos = computed<GalleryPhoto[]>(() => {
    const cosplay = this.cosplayResource.value();
    const id = this.id();
    if (!cosplay || !id) {
      return [];
    }

    return (cosplay.imgGalleryUrls ?? []).map((image, i) => {
      const big = stripAssetsPrefix(image.big) ?? '';
      const small = stripAssetsPrefix(image.small) ?? big;
      const medium = stripAssetsPrefix(image.medium);
      return this.toGalleryPhoto({
        id,
        thumbSrc: small,
        fullSrc: big,
        mediumSrc: medium,
        alt: `${cosplay.name} photo ${i + 1}`,
      });
    });
  });

  protected readonly wipPhotos = computed<GalleryPhoto[]>(() => {
    const cosplay = this.cosplayResource.value();
    const id = this.id();
    if (!cosplay || !id) {
      return [];
    }

    return (cosplay.wipGalleryUrls ?? []).map((wip, i) => {
      const src = stripAssetsPrefix(wip.img) ?? '';
      return this.toGalleryPhoto({
        id,
        thumbSrc: this.wipThumbSrc(src),
        fullSrc: src,
        alt: wip.desc || `${cosplay.name} WIP photo ${i + 1}`,
        caption: wip.desc,
      });
    });
  });

  // WIP photos only ever get a single "img" field in Firestore (unlike
  // the main gallery's separate big/small/medium fields), so rather
  // than migrating every existing document, the small/thumbnail
  // variant's path is derived straight from that one field — it's just
  // the same filename under a "wip/s/" folder instead of "wip/".
  private wipThumbSrc(src: string): string {
    return src.replace(/\/wip\/([^/]+)$/, '/wip/s/$1');
  }

  // Looks up each image's real size in dimensions.json, keyed by its
  // path relative to that cosplay's own folder (e.g. "s/1.jpg"). Falls
  // back to a reasonable guess for the handful of files the generator
  // script couldn't parse, rather than breaking the lightbox for them.
  // When a medium-size variant exists too, builds a srcset so phones
  // load that instead of the full desktop-res photo.
  private toGalleryPhoto(options: {
    id: string;
    thumbSrc: string;
    fullSrc: string;
    mediumSrc?: string;
    alt: string;
    caption?: string;
  }): GalleryPhoto {
    const { id, thumbSrc, fullSrc, mediumSrc, alt, caption } = options;
    const dims = this.dimensionsResource.value() ?? {};
    const prefix = `cosplay/${id}/`;
    const dimsFor = (src: string) => dims[src.replace(prefix, '')];

    const thumb = dimsFor(thumbSrc);
    const full = dimsFor(fullSrc);
    const medium = mediumSrc ? dimsFor(mediumSrc) : undefined;

    const fullSrcset =
      mediumSrc && medium && full
        ? `${mediumSrc} ${medium.width}w, ${fullSrc} ${full.width}w`
        : undefined;

    return {
      thumbSrc,
      thumbWidth: thumb?.width ?? 270,
      thumbHeight: thumb?.height ?? 405,
      fullSrc,
      fullWidth: full?.width ?? 667,
      fullHeight: full?.height ?? 1000,
      fullSrcset,
      alt,
      caption,
    };
  }
}
